### ISSUE TITLE
IPFS Example Link doesn't load

### ISSUE THREAD

**Issue by Blindripper** [tqtezos/nft-tutorial#6]
5. "You can inspect the file on the web by opening a URL https://ipfs.io/ipfs/<ipfs_cid>. For our example, the URL would be https://ipfs.io/ipfs/QmRyTc9KbD7ZSkmEf4e7fk6A44RPciW5pM4iyqRGrhbyvj"

**Comment by emishur** [comment]
The file pin was lost. Should be working now.
